# Generated by Django 5.0.3 on 2024-03-11 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraccount_is_jobseeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_jobseeker',
        ),
    ]
