# Generated by Django 5.0.3 on 2024-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=255)),
                ('date_posted', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('saved', models.PositiveIntegerField(default=0)),
                ('applied', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='saved_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=255)),
                ('date_posted', models.DateField()),
            ],
        ),
    ]
