# Generated by Django 5.0.3 on 2024-03-10 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.EmailField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('salary_package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefits', models.TextField()),
                ('required_skills', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('experience_required_years', models.DecimalField(decimal_places=2, max_digits=4)),
                ('education_required', models.TextField()),
                ('job_status', models.CharField(choices=[('hiring', 'Hiring'), ('filled', 'Filled')], default='hiring', max_length=20)),
                ('is_saved', models.BooleanField(default=False)),
            ],
        ),
    ]
