# Generated by Django 5.0.3 on 2024-03-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='location',
            new_name='post',
        ),
    ]
