# Generated by Django 5.0.3 on 2024-03-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='company',
            new_name='company_email',
        ),
        migrations.AlterUniqueTogether(
            name='jobs',
            unique_together={('title', 'company_email')},
        ),
    ]
