# Generated by Django 5.0.3 on 2024-03-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_company_jobs_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='is_saved',
        ),
    ]
