# Generated by Django 5.0.3 on 2024-03-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobs_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='loc',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
