# Generated by Django 5.0.3 on 2024-03-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_jobs_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobs',
            unique_together={('title', 'company_email', 'posted_date')},
        ),
    ]
