# Generated by Django 5.0.3 on 2024-03-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location_table',
            },
        ),
        migrations.CreateModel(
            name='CompanyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('project_duration', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
            ],
            options={
                'db_table': 'compproject_table',
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('about_you', models.TextField()),
                ('education', models.TextField()),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('profile_link', models.URLField(blank=True, null=True)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('certificates', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobseeker_table',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('project_name', models.CharField(max_length=200)),
                ('project_duration', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'proj_table',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'skill_table',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('contact_no', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('min_salary_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company_picture', models.ImageField(blank=True, null=True, upload_to='company_pictures/')),
                ('instagram_account', models.URLField(blank=True, null=True)),
                ('facebook_account', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('location', models.ManyToManyField(to='Profile.companylocation')),
            ],
            options={
                'db_table': 'company_table',
            },
        ),
    ]
