# Generated by Django 5.0.3 on 2024-03-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
    ]
