# Generated by Django 5.0.3 on 2024-03-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_company_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylocation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='companyprojects',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='companylocation',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='companyprojects',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
    ]
