# Generated by Django 5.0.3 on 2024-03-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_remove_companylocation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
