# Generated by Django 5.0.3 on 2024-03-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_jobseeker_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
