# Generated by Django 5.0.3 on 2024-03-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_jobseeker_cgpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cnic',
            new_name='company',
        ),
    ]
