# Generated by Django 5.0.3 on 2024-03-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_rename_cnic_project_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companylocation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companyprojects',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jobseeker',
            table=None,
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
        migrations.AlterModelTable(
            name='skill',
            table=None,
        ),
    ]
