# Generated by Django 5.0.3 on 2024-03-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_alter_company_table_alter_companylocation_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='ircompany',
        ),
        migrations.AlterModelTable(
            name='companylocation',
            table='companylocations',
        ),
        migrations.AlterModelTable(
            name='companyprojects',
            table='companyprojects',
        ),
        migrations.AlterModelTable(
            name='jobseeker',
            table='jobseeker',
        ),
        migrations.AlterModelTable(
            name='project',
            table='jobseekerprojects',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skillss',
        ),
    ]
