# Generated by Django 4.2.4 on 2024-03-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_password', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('company_dob', models.CharField(max_length=100)),
                ('company_au', models.TextField()),
                ('company_mission', models.TextField()),
                ('company_services', models.TextField()),
                ('company_logo', models.ImageField(default='backend/images/default.png', upload_to='backend/images')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=300)),
                ('grad_year', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=10)),
                ('f_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=1)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('applicant_email', models.CharField(max_length=100)),
                ('questions', models.TextField()),
                ('answers', models.TextField()),
                ('e_result', models.CharField(max_length=100)),
                ('t_result', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('req_exp', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('key_responsibilities', models.TextField()),
                ('required_skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_password', models.CharField(max_length=100)),
                ('applicant_email', models.CharField(max_length=100)),
                ('applicant_location', models.CharField(max_length=100)),
                ('applicant_address', models.TextField()),
                ('applicant_dob', models.CharField(max_length=100)),
                ('applicant_profession', models.CharField(max_length=100)),
                ('applicant_education', models.CharField(max_length=100)),
                ('applicant_skills', models.TextField()),
                ('applicant_workexp', models.CharField(max_length=100)),
                ('applicant_pfp', models.ImageField(default='backend/images/default.png', upload_to='backend/images')),
            ],
        ),
        migrations.CreateModel(
            name='JobsSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('applicant_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('f_key', models.CharField(max_length=100)),
            ],
        ),
    ]
