# Generated by Django 4.2.4 on 2024-03-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_company_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applied',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='saved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='views',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
