# Generated by Django 4.2.4 on 2024-03-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_jobs_applied_jobs_saved_jobs_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
