# Generated by Django 5.0.3 on 2024-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='int_evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('interview_date', models.DateField()),
                ('personality_test_result', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='jobinterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_first_name', models.CharField(max_length=255)),
                ('applicant_last_name', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('date_and_time', models.DateTimeField()),
                ('job_title', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_posted_date', models.DateField()),
            ],
        ),
    ]
