# Generated by Django 5.0.3 on 2024-03-15 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinterview',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='jobinterview',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
